### PR TITLE
Fixes #37 Overlapping Card Bug and improves card ui

### LINKED ISSUE #37: Cards in UI Overview overlay
The Cards in the UI Overlay overlap each other. This should be fixed.
screenshot_2015-09-13_02-03-13_ 0200

### PR DESCRIPTION
**Pull request by joker234**

### CODE REVIEW

**Comment by Merovius** [comment]
Please resolve the conflicts

**Comment by Merovius** [comment]
Also, the commit message should have the form:
```
Overlapping Card Bug and improves card ui

Fixes #37
```
I prefer this format.

**Comment by joker234** [comment]
why should the commit message like that? Who cares about issue numbers in the first line?

**Comment by Merovius** [comment]
> why should the commit message like that? Who cares about issue numbers in the first line?

I agree that it is somewhat nit-picky, but I want a consistent choice for this. The first line is special, as it's the only one shown by git log --oneline and also the only one shown in the commit-log on github. So it does matter what is in the first line and what isn't. Information about bugfixes shouldn't be in such a prominent place, in my opinion.

**Comment by Merovius** [comment]
I manually cherry-picked the change now with a fixed commit message.

**Comment by joker234** [comment]
now the commit message is really misunderstanding but do what you want

**Pull request closed without merging**
